#!/bin/bash

# Script writen by Duanel Garrido Milan
# License GPLv3

APACHE_CONF_FILE="/etc/httpd/conf/httpd.conf"
PHP_INI="/etc/php/php.ini"

echo "#############################################"
echo ">> LAMP server for Manjaro/Arch-based distros"

if (( $EUID != 0 )); then
    echo "Please run as root"
    exit 1
fi

echo ">> Ensuring that the system is up-to-date"
pacman -Syyu --noconfirm

if [ "$?" -ne "0" ]; then
  echo "Sorry, something went wrong. Check you internet connection"
  exit 1
fi

echo ">> Done!"
echo ">> Installation of nessesary packages"

pacman -S apache mariadb php php-apache --noconfirm 

if [ "$?" -ne "0" ]; then
  echo "Sorry, cannot install any packages. Check you internet connection"
  exit 1
fi

echo ">> Done!"
echo ">> Enabling PHP for Apache"

sed -i.bak '/LoadModule mpm_event_module/s/^/#/g' $APACHE_CONF_FILE ## Comment out
sed -i.bak '/LoadModule mpm_prefork_module/s/^#//g' $APACHE_CONF_FILE ## Uncomment

echo "LoadModule php7_module modules/libphp7.so" >> $APACHE_CONF_FILE
echo "AddHandler php7-script php" >> $APACHE_CONF_FILE
echo "Include conf/extra/php7_module.conf" >> $APACHE_CONF_FILE

sed -i.bak '/extension=mysql.so/s/^/;/g' $PHP_INI ## Comment out
sed -i.bak '/extension=mysql.so/s/^;//g' $PHP_INI ## Uncomment

echo "Enabling and starting Apache"
systemctl enable httpd
systemctl restart httpd

if [ "$?" -ne "0" ]; then
  systemctl status httpd
  exit 1
fi

echo ">> Setting up MariaDB" 
mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

echo "Enabling and starting MariaDB"
systemctl enable mysqld
systemctl start mysqld

if [ "$?" -ne "0" ]; then
  systemctl status mysqld
  exit 1
fi

mysql_secure_installation

if [ "$?" -ne "0" ]; then
  echo "Something went wrong. Please check the logs for more information."
  exit 1
fi

echo ">> Done! Installation completed!
